site_name: MindStudio GitHub Docs
site_description: MindStudio tools documentation collection
site_url: ""

docs_dir: .
site_dir: ../site
theme:
  name: readthedocs

use_directory_urls: true

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - same-dir

validation:
  nav:
    omitted_files: ignore
  links:
    not_found: ignore
    anchors: ignore
    absolute_links: ignore
    unrecognized_links: ignore

nav:
  - Home: README.md
  - Tools:
      - msdebug: msdebug/README.md
      - msinsight: msinsight/README.md
      - msit: msit/README.md
      - mskl: mskl/README.md
      - mskpp: mskpp/README.md
      - msmemscope: msmemscope/README.md
      - msmodeling: msmodeling/README.md
      - msmodelslim: msmodelslim/README.md
      - msmonitor: msmonitor/README.md
      - msopcom: msopcom/README.md
      - msopgen: msopgen/README.md
      - msopmodeling: msopmodeling/README.md
      - msopprof: msopprof/README.md
      - msoptuner: msoptuner/README.md
      - msot: msot/README.md
      - msprobe: msprobe/README.md
      - msprof: msprof/README.md
      - msprof-analyze: msprof-analyze/README.md
      - mspti: mspti/README.md
      - mssanitizer: mssanitizer/README.md
      - msserviceprofiler: msserviceprofiler/README.md
      - mstt: mstt/README.md
      - mstx: mstx/README.md

exclude_docs: |
  .git/
  .devin/
  .idea/
  .venv/
  .mkdocs*/
  .readthedocs.yaml
  mkdocs.yml
  requirements.txt
  site/
